export const playersData = [
    {
        id: 1,
        name: "Adam Lenz",
        position: "Back",
        number: 1,
        height: "6'2\"",
        weight: "245 lbs",
        age: 28,
        imageUrl: "/team/AdamLenz.png",
        description: "A powerful forward known for strength in the scrum and lineout ability. Has been with the team for 5 seasons and is a natural leader on the field.",
    },
    {
        id: 3,
        name: "Alexander Cavanaugh",
        position: "Forward",
        number: 3,
        height: "6'5\"",
        weight: "255 lbs",
        age: 29,
        imageUrl: "/team/AlexanderCavanaugh.png",
        description: "A dominant lock who excels in the lineout and provides powerful drives in open play. Work rate is exceptional for a player of this size.",
    },
    {
        id: 4,
        name: "Agustin Maurizi",
        position: "Back",
        number: 4,
        height: "6'0\"",
        weight: "205 lbs",
        age: 26,
        imageUrl: "/team/AgustinMaurizi.png",
        description: "A fullback with excellent positional awareness and counter-attacking ability. Safe hands under the high ball make for a reliable last line of defense.",
    },
    {
        id: 6,
        name: "Benjamin Story",
        position: "Back",
        number: 6,
        height: "5'10\"",
        weight: "185 lbs",
        age: 24,
        imageUrl: "/team/BenStory.png",
        description: "A scrum-half with quick service and excellent game management. Box kicking is a key part of the team's territorial strategy.",
    },
    {
        id: 7,
        name: "Brandon Chatmon",
        position: "Forward",
        number: 7,
        height: "6'0\"",
        weight: "260 lbs",
        age: 30,
        imageUrl: "/team/BrandonChatmon.png",
        description: "A tighthead prop who anchors the scrum. Technical scrummaging ability and work in the tight has earned international recognition.",
    },
    {
        id: 8,
        name: "Carlos Lavayen",
        position: "Back",
        number: 8,
        height: "6'2\"",
        weight: "215 lbs",
        age: 26,
        imageUrl: "/placeholder.svg?height=400&width=400",
        description: "An outside center with pace and power. Line-breaking ability and offloading skills create numerous opportunities for the team.",
    },
    {
        id: 9,
        name: "Casey Kropp",
        position: "Forward",
        number: 9,
        height: "6'3\"",
        weight: "240 lbs",
        age: 28,
        imageUrl: "/placeholder.svg?height=400&width=400",
        description: "A number 8 with excellent ball control at the base of the scrum. Carrying ability and link play between forwards and backs is exceptional.",
    },
    {
        id: 10,
        name: "Key Cooper",
        position: "Back",
        number: 10,
        height: "5'11\"",
        weight: "195 lbs",
        age: 25,
        imageUrl: "/team/KeyCooper.png",
        description: "A wing with electric pace and finishing ability. Defensive positioning and work under the high ball are equally impressive.",
    },
    {
        id: 11,
        name: "Clarence Jackson",
        position: "Forward",
        number: 11,
        height: "6'2\"",
        weight: "245 lbs",
        age: 27,
        imageUrl: "/placeholder.svg?height=400&width=400",
        description: "A versatile forward with excellent ball-handling skills and strong defensive capabilities.",
    },
    {
        id: 12,
        name: "Darian Mejia",
        position: "Back",
        number: 12,
        height: "5'10\"",
        weight: "190 lbs",
        age: 24,
        imageUrl: "/team/DarianMejia.png",
        description: "A dynamic back with great acceleration and ability to find gaps in the defense.",
    },
    {
        id: 13,
        name: "David Webster",
        position: "Forward",
        number: 13,
        height: "6'4\"",
        weight: "250 lbs",
        age: 29,
        imageUrl: "/placeholder.svg?height=400&width=400",
        description: "A powerhouse in the scrum with exceptional leadership qualities.",
    },
    {
        id: 14,
        name: "Dylan Clark",
        position: "Back",
        number: 14,
        height: "6'0\"",
        weight: "200 lbs",
        age: 26,
        imageUrl: "/placeholder.svg?height=400&width=400",
        description: "An agile back with excellent kicking skills and defensive positioning.",
    },
    {
        id: 15,
        name: "Eduardo Chavez-Marr",
        position: "Forward",
        number: 15,
        height: "6'1\"",
        weight: "235 lbs",
        age: 28,
        imageUrl: "/placeholder.svg?height=400&width=400",
        description: "A reliable forward known for consistency in set pieces and open play.",
    },
    {
        id: 16,
        name: "Ernesto Lavayen",
        position: "Back",
        number: 16,
        height: "5'11\"",
        weight: "195 lbs",
        age: 25,
        imageUrl: "/placeholder.svg?height=400&width=400",
        description: "A skilled playmaker with excellent vision and distribution abilities.",
    },
    {
        id: 17,
        name: "Ezequiel Muniz",
        position: "Forward",
        number: 17,
        height: "6'3\"",
        weight: "245 lbs",
        age: 27,
        imageUrl: "/placeholder.svg?height=400&width=400",
        description: "A mobile forward with strong carrying ability and work rate.",
    },
    {
        id: 18,
        name: "Freddy Rojas",
        position: "Back",
        number: 18,
        height: "5'8\"",
        weight: "255 lbs",
        age: 24,
        imageUrl: "team/FreddyRojas.png",
        description: "An elusive runner with natural attacking instincts.",
    },
    {
        id: 19,
        name: "Ian Ross",
        position: "Forward",
        number: 19,
        height: "6'2\"",
        weight: "240 lbs",
        age: 26,
        imageUrl: "/placeholder.svg?height=400&width=400",
        description: "A technically sound forward with excellent lineout skills.",
    },
    {
        id: 20,
        name: "Ian Tirado",
        position: "Back",
        number: 20,
        height: "6'0\"",
        weight: "200 lbs",
        age: 25,
        imageUrl: "/placeholder.svg?height=400&width=400",
        description: "A versatile back who can cover multiple positions with effectiveness.",
    },
    {
        id: 21,
        name: "Joey Avila",
        position: "Forward",
        number: 21,
        height: "6'1\"",
        weight: "230 lbs",
        age: 28,
        imageUrl: "/placeholder.svg?height=400&width=400",
        description: "A dynamic forward with exceptional breakdown skills.",
    },
    {
        id: 22,
        name: "Jonathan Colecraft-Peters",
        position: "Back",
        number: 22,
        height: "5'11\"",
        weight: "190 lbs",
        age: 26,
        imageUrl: "/team/JonPeters.png",
        description: "A creative back with excellent footwork and passing ability.",
    },
    {
        id: 23,
        name: "Joseph Juliano",
        position: "Forward",
        number: 23,
        height: "6'3\"",
        weight: "245 lbs",
        age: 29,
        imageUrl: "/placeholder.svg?height=400&width=400",
        description: "A powerful scrummager with strong leadership qualities.",
    },
    {
        id: 24,
        name: "Juan Santos",
        position: "Back",
        number: 24,
        height: "5'10\"",
        weight: "185 lbs",
        age: 25,
        imageUrl: "/placeholder.svg?height=400&width=400",
        description: "A quick and agile player with excellent defensive skills.",
    },
    {
        id: 25,
        name: "JuCorie Jones",
        position: "Forward",
        number: 25,
        height: "6'2\"",
        weight: "235 lbs",
        age: 27,
        imageUrl: "/placeholder.svg?height=400&width=400",
        description: "An athletic forward with exceptional aerial skills.",
    },
    {
        id: 26,
        name: "Nabil Arabi El Eter",
        position: "Back",
        number: 26,
        height: "6'0\"",
        weight: "195 lbs",
        age: 24,
        imageUrl: "/team/NabilArabi.png",
        description: "A skilled playmaker with excellent game management abilities.",
    },
    {
        id: 27,
        name: "Nasyir-Michel Boutin",
        position: "Forward",
        number: 27,
        height: "6'4\"",
        weight: "255 lbs",
        age: 28,
        imageUrl: "/placeholder.svg?height=400&width=400",
        description: "A dominant presence in the set piece with strong carrying ability.",
    },
    {
        id: 28,
        name: "Nate Lozada",
        position: "Back",
        number: 28,
        height: "5'11\"",
        weight: "190 lbs",
        age: 25,
        imageUrl: "/team/NateLozada.png",
        description: "A reliable defender with good distribution skills.",
    },
    {
        id: 29,
        name: "Nicolas Cook",
        position: "Forward",
        number: 29,
        height: "6'1\"",
        weight: "230 lbs",
        age: 26,
        imageUrl: "/placeholder.svg?height=400&width=400",
        description: "A mobile forward with excellent work rate and defensive capabilities.",
    },
    {
        id: 30,
        name: "Paul Walton",
        position: "Back",
        number: 30,
        height: "6'0\"",
        weight: "200 lbs",
        age: 27,
        imageUrl: "/placeholder.svg?height=400&width=400",
        description: "A skilled tactician with strong kicking game.",
    },
    {
        id: 31,
        name: "Richard Hoch",
        position: "Forward",
        number: 31,
        height: "6'3\"",
        weight: "245 lbs",
        age: 29,
        imageUrl: "/placeholder.svg?height=400&width=400",
        description: "A seasoned forward with excellent technical skills.",
    },
    {
        id: 32,
        name: "Tristan Carter",
        position: "Back",
        number: 32,
        height: "5'10\"",
        weight: "185 lbs",
        age: 24,
        imageUrl: "/placeholder.svg?height=400&width=400",
        description: "An explosive runner with natural attacking instincts.",
    },
    {
        id: 33,
        name: "Tyler Blyth",
        position: "Forward",
        number: 33,
        height: "6'2\"",
        weight: "240 lbs",
        age: 28,
        imageUrl: "/placeholder.svg?height=400&width=400",
        description: "A reliable forward with strong set-piece skills.",
    },
    {
        id: 34,
        name: "Tyler Cooper",
        position: "Back",
        number: 34,
        height: "6'0\"",
        weight: "195 lbs",
        age: 26,
        imageUrl: "/placeholder.svg?height=400&width=400",
        description: "A versatile back with excellent defensive positioning.",
    },
    {
        id: 35,
        name: "Victor Morales",
        position: "Forward",
        number: 35,
        height: "6'1\"",
        weight: "235 lbs",
        age: 27,
        imageUrl: "/team/VictorMorales.jpg",
        description: "A dynamic forward with strong ball-carrying abilities.",
    }
];