export const organizationSchema = {
    '@context': 'https://schema.org',
    '@type': ['SportsOrganization', 'LocalBusiness'],
    name: 'Central Florida Claymores Rugby Football Club',
    alternateName: ['Central Florida Claymores RFC', 'Orlando Claymores Rugby', 'CF Claymores'],
    url: 'https://www.claymoresrfc.com',
    logo: 'https://www.claymoresrfc.com/assets/logo.png',
    image: 'https://www.claymoresrfc.com/assets/logo.png',
    foundingDate: '2018',
    sport: 'Rugby Union',
    telephone: '(407) 501-9953',
    description: "Orlando's USA Rugby D3 club. The Central Florida Claymores RFC compete in the Florida Rugby Union and welcome players of all skill levels — no experience required.",
    address: {
        '@type': 'PostalAddress',
        streetAddress: '4801 W Colonial Dr',
        addressLocality: 'Orlando',
        addressRegion: 'FL',
        postalCode: '32808',
        addressCountry: 'US',
    },
    geo: {
        '@type': 'GeoCoordinates',
        latitude: 28.5567,
        longitude: -81.4312,
    },
    areaServed: [
        { '@type': 'City', name: 'Orlando' },
        { '@type': 'City', name: 'Ocoee' },
        { '@type': 'City', name: 'Apopka' },
        { '@type': 'City', name: 'Winter Garden' },
        { '@type': 'City', name: 'Windermere' },
        { '@type': 'City', name: 'Maitland' },
        { '@type': 'City', name: 'Winter Park' },
        { '@type': 'City', name: 'Altamonte Springs' },
        { '@type': 'City', name: 'Casselberry' },
        { '@type': 'City', name: 'Winter Springs' },
        { '@type': 'City', name: 'Longwood' },
        { '@type': 'City', name: 'Lake Mary' },
        { '@type': 'City', name: 'Sanford' },
        { '@type': 'City', name: 'Oviedo' },
        { '@type': 'City', name: 'Kissimmee' },
        { '@type': 'City', name: 'St. Cloud' },
        { '@type': 'City', name: 'Clermont' },
        { '@type': 'City', name: 'Minneola' },
        { '@type': 'AdministrativeArea', name: 'Horizon West' },
        { '@type': 'AdministrativeArea', name: 'Lake Nona' },
        { '@type': 'AdministrativeArea', name: 'Dr. Phillips' },
        { '@type': 'AdministrativeArea', name: 'East Orlando' },
        { '@type': 'AdministrativeArea', name: 'Waterford Lakes' },
        { '@type': 'AdministrativeArea', name: 'Avalon Park' },
        { '@type': 'AdministrativeArea', name: 'Bithlo' },
        { '@type': 'AdministrativeArea', name: 'Central Florida' },
        { '@type': 'AdministrativeArea', name: 'Orange County, FL' },
        { '@type': 'AdministrativeArea', name: 'Seminole County, FL' },
        { '@type': 'AdministrativeArea', name: 'Osceola County, FL' },
        { '@type': 'AdministrativeArea', name: 'Lake County, FL' },
    ],
    email: 'claymoresrfc@gmail.com',
    memberOf: [
        {
            '@type': 'SportsOrganization',
            name: 'Florida Rugby Union',
            url: 'https://rugbyfl.com',
        },
        {
            '@type': 'SportsOrganization',
            name: 'USA Rugby',
            url: 'https://usarugby.org',
        },
    ],
    sameAs: [
        'https://www.facebook.com/claymoresrugby/',
        'https://www.instagram.com/claymoresrugby_/',
    ],
}
